#!/bin/sh

if [ ."$(uci -q get aria2.main)" != ."aria2" ]; then
	uci -q batch <<-EOF >/dev/null
		add aria2 aria2
		rename aria2.@aria2[-1]="main"
		set aria2.main.enabled=0
		set aria2.main.dir="/var/run/aria2"
		set aria2.main.config_dir="/var/etc/aria2"
		add_list aria2.main.header=""
		add_list aria2.main.bt_tracker=""
    		add_list aria2.main.split="128"
    		add_list aria2.main.min_split_size="100K"
    		add_list aria2.main.max_connection_per_server="128"
		add_list aria2.main.extra_settings="dht-file-path=/usr/share/aria2/dht.dat"
		commit aria2
	EOF
fi

exit 0
